In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [3]:
env = gym.make("FrozenLake-v1")

In [4]:
action_space = env.action_space.n
state_space = env.observation_space.n
q_table = np.zeros((state_space,action_space))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
num_episodes = 10000
max_steps_ep = 100

lr = 0.1
dr = 0.99

expr_rate = 1
max_expr_rate = 1
min_expr_rate = 0.01
expr_decay_rate = 0.01

In [22]:
all_rewards = []
for episode in range(num_episodes):
    if episode%1000 == 0:
        print(episode," processing")
    state = env.reset()
    done = False
    rewards_curr = 0
    for step in range(max_steps_ep):
        expr_thresh = random.uniform(0,1)
        if expr_thresh > expr_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)
        #update Q-table
        q_table[state,action] = q_table[state,action]*(1 - lr) + \
        lr*(reward + dr*np.max(q_table[new_state,:]))
        
        state = new_state
        rewards_curr += reward
        if done == True:
            break
    expr_rate = min_expr_rate + (max_expr_rate - min_expr_rate)* \
    np.exp(-expr_decay_rate*episode)
    all_rewards.append(rewards_curr)
rewards_per_thousand = np.split(np.array(all_rewards), num_episodes/1000)
count = 1000
print("Avg reward per thousand eps\n")
for r in rewards_per_thousand:
    print(count, ": ",str(sum(r/1000)))
    count += 1000
print("\n\n Q-Table\n")
print(q_table)

0  processing
1000  processing
2000  processing
3000  processing
4000  processing
5000  processing
6000  processing
7000  processing
8000  processing
9000  processing
Avg reward per thousand eps

1000 :  0.5250000000000004
2000 :  0.6970000000000005
3000 :  0.6780000000000005
4000 :  0.6810000000000005
5000 :  0.6630000000000005
6000 :  0.7060000000000005
7000 :  0.6890000000000005
8000 :  0.6960000000000005
9000 :  0.6920000000000005
10000 :  0.6400000000000005


 Q-Table

[[0.49997932 0.45967431 0.4585543  0.4607047 ]
 [0.34766867 0.28931927 0.36644161 0.4533188 ]
 [0.38790515 0.3694081  0.40475457 0.42428988]
 [0.22450105 0.26038383 0.2541063  0.40790761]
 [0.51793039 0.2533722  0.34458947 0.40970935]
 [0.         0.         0.         0.        ]
 [0.19654992 0.11770266 0.28122684 0.17893268]
 [0.         0.         0.         0.        ]
 [0.43992707 0.29972534 0.40163498 0.55979618]
 [0.48819983 0.63189999 0.37806951 0.32704301]
 [0.6384719  0.32605741 0.32550694 0.30757798]
 [0.